#!/bin/sh
# Put viewer in the desktop's application list, so it starts from an icon
# instead of a command line.
#
#   ./install_shortcut.sh                                  local viewer
#   ./install_shortcut.sh --host user@server               + an entry that
#   ./install_shortcut.sh --host user@server --path /data/run42   connects there
#   ./install_shortcut.sh --uninstall
#
# Linux  -> ~/.local/share/applications/viewer.desktop (+ the icon in the
#           hicolor theme). The Exec line points at the binary where it already
#           is, so a `git pull` of the binaries branch updates what the icon
#           starts without touching the entry.
# macOS  -> ~/Applications/viewer.app, a wrapper whose executable execs that
#           same binary: a bundle is the only thing the Dock will show an icon
#           and a name for.
#
# Nothing is installed system-wide and nothing needs root.
set -eu

self=$(cd "$(dirname "$0")" && pwd)
host=''
rpath='~'
name='viewer'
uninstall=0
bin=''
icon=''

usage() {
    sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'
    exit "${1:-0}"
}

while [ $# -gt 0 ]; do
    case "$1" in
        --host)      host=${2:?--host needs user@server}; shift 2 ;;
        --path)      rpath=${2:?--path needs a directory}; shift 2 ;;
        --bin)       bin=${2:?--bin needs a path}; shift 2 ;;
        --icon)      icon=${2:?--icon needs a png}; shift 2 ;;
        --name)      name=${2:?--name needs a string}; shift 2 ;;
        --uninstall) uninstall=1; shift ;;
        -h|--help)   usage 0 ;;
        *)           echo "unknown option: $1" >&2; usage 2 ;;
    esac
done

find_first() {
    for c in "$@"; do
        [ -f "$c" ] && { (cd "$(dirname "$c")" && printf '%s/%s\n' "$(pwd)" "$(basename "$c")"); return 0; }
    done
    return 1
}

case "$(uname -s)" in
    Darwin) plat=mac; sub=macos-arm64 ;;
    *)      plat=linux; sub=linux-x64 ;;
esac

remote_url() {
    case "$rpath" in
        ''|'~')  printf 'ssh://%s\n' "$host" ;;
        /*)      printf 'ssh://%s%s\n' "$host" "$rpath" ;;
        '~/'*)   printf 'ssh://%s/~/%s\n' "$host" "${rpath#\~/}" ;;
        *)       printf 'ssh://%s/~/%s\n' "$host" "$rpath" ;;
    esac
}

# ---- uninstall --------------------------------------------------------------
if [ "$uninstall" = 1 ]; then
    if [ "$plat" = mac ]; then
        for app in "$HOME/Applications/$name.app" "$HOME/Applications/$name (remote).app"; do
            [ -d "$app" ] && { rm -rf "$app"; echo "removed  $app"; }
        done
    else
        d=$HOME/.local/share/applications
        for f in "$d/$name.desktop" "$d/$name-remote.desktop"; do
            [ -f "$f" ] && { rm -f "$f"; echo "removed  $f"; }
        done
        rm -f "$HOME/.local/share/icons/hicolor/256x256/apps/$name.png"
        command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database "$d" || true
    fi
    echo 'done.'
    exit 0
fi

# ---- what to point at -------------------------------------------------------
[ -n "$bin" ] || bin=$(find_first \
    "$self/viewer" "$self/$sub/viewer" "$self/../$sub/viewer" \
    "$self/../build/viewer" "$self/../build-mingw/viewer" "$self/../build-ninja/viewer") || {
        echo "viewer binary not found near $self - pass --bin <path>" >&2; exit 1; }
[ -x "$bin" ] || { echo "not executable: $bin" >&2; exit 1; }
echo "viewer:  $bin"

# generated by the build (mkicon); shipped next to the binaries by CI
[ -n "$icon" ] || icon=$(find_first \
    "$self/icons/viewer.png" "$self/viewer.png" "$self/$sub/icons/viewer.png" \
    "$self/../$sub/icons/viewer.png" \
    "$self/../build/icons/viewer.png" "$self/../build-mingw/icons/viewer.png") || icon=''
[ -n "$icon" ] && echo "icon:    $icon" || echo "icon:    (none found - build once to generate it)"

# ---- macOS: a .app wrapper --------------------------------------------------
if [ "$plat" = mac ]; then
    make_app() {                       # $1 = app name, $2 = argument to pass
        app="$HOME/Applications/$1.app"
        rm -rf "$app"
        mkdir -p "$app/Contents/MacOS" "$app/Contents/Resources"
        cat > "$app/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
    <key>CFBundleName</key><string>$1</string>
    <key>CFBundleDisplayName</key><string>$1</string>
    <key>CFBundleIdentifier</key><string>com.klimemam.viewer</string>
    <key>CFBundleExecutable</key><string>launch</string>
    <key>CFBundleIconFile</key><string>viewer</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>0.1</string>
    <key>NSHighResolutionCapable</key><true/>
</dict></plist>
PLIST
        # exec, not copy: the bundle keeps working after the binary is rebuilt
        cat > "$app/Contents/MacOS/launch" <<LAUNCH
#!/bin/sh
exec "$bin" $2 "\$@"
LAUNCH
        chmod +x "$app/Contents/MacOS/launch"
        if [ -n "$icon" ] && command -v sips >/dev/null 2>&1 && command -v iconutil >/dev/null 2>&1; then
            set=$(mktemp -d)/viewer.iconset
            mkdir -p "$set"
            for s in 16 32 128 256 512; do
                sips -z $s $s "$icon" --out "$set/icon_${s}x${s}.png" >/dev/null 2>&1 || true
                d=$((s * 2))
                sips -z $d $d "$icon" --out "$set/icon_${s}x${s}@2x.png" >/dev/null 2>&1 || true
            done
            iconutil -c icns "$set" -o "$app/Contents/Resources/viewer.icns" 2>/dev/null || true
            rm -rf "$set"
        fi
        echo "created  $app"
    }
    make_app "$name" ''
    [ -n "$host" ] && make_app "$name (remote)" "'$(remote_url)'"
    echo ''
    echo 'Open it once from ~/Applications, then keep it in the Dock (right-click > Options > Keep in Dock).'
    exit 0
fi

# ---- Linux: a .desktop entry ------------------------------------------------
appdir=$HOME/.local/share/applications
mkdir -p "$appdir"
iconref=$name
if [ -n "$icon" ]; then
    icondir=$HOME/.local/share/icons/hicolor/256x256/apps
    mkdir -p "$icondir"
    cp -f "$icon" "$icondir/$name.png"
    command -v gtk-update-icon-cache >/dev/null 2>&1 &&
        gtk-update-icon-cache -q -f -t "$HOME/.local/share/icons/hicolor" 2>/dev/null || true
else
    iconref=image-x-generic
fi

write_entry() {                        # $1 = file, $2 = visible name, $3 = args
    cat > "$1" <<DESKTOP
[Desktop Entry]
Type=Application
Version=1.0
Name=$2
Comment=Engineering image viewer - npy / RAW / Bayer, measured in place
Exec="$bin" $3%F
Icon=$iconref
Terminal=false
Categories=Graphics;Science;RasterGraphics;Viewer;
Keywords=npy;raw;bayer;image;sensor;
StartupNotify=true
StartupWMClass=viewer
DESKTOP
    chmod +x "$1"
    echo "created  $1"
}

# the url is double-quoted because "~" is a reserved character in an Exec line
write_entry "$appdir/$name.desktop" "$name" ''
[ -n "$host" ] && write_entry "$appdir/$name-remote.desktop" "$name ($host)" "\"$(remote_url)\" "

command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database "$appdir" 2>/dev/null || true

echo ''
echo "It is in the application menu now (search for \"$name\")."
echo 'Drag it to the dock/panel to keep it there, or right-click the running window.'
if [ -z "$host" ]; then
    echo 'For an entry that connects to a server on startup:'
    echo "    $0 --host user@server --path /data/run42"
fi
