# Writes a header naming the commit this binary was built from, at BUILD time -
# a configure-time hash goes stale the moment you commit, and this string ends
# up in exported data as provenance.
#
# Run in script mode:  cmake -DOUT=<header> -DSRCDIR=<repo> -P gitversion.cmake
#
# A tree with uncommitted changes must not claim to BE the commit: it says
# "<hash>+local". No git, or no repository (a tarball build), says "unknown".

set(_hash "unknown")

find_package(Git QUIET)
if(GIT_FOUND)
    execute_process(COMMAND "${GIT_EXECUTABLE}" rev-parse --short=12 HEAD
                    WORKING_DIRECTORY "${SRCDIR}"
                    OUTPUT_VARIABLE _h OUTPUT_STRIP_TRAILING_WHITESPACE
                    ERROR_QUIET RESULT_VARIABLE _rc)
    if(_rc EQUAL 0 AND _h)
        set(_hash "${_h}")
        execute_process(COMMAND "${GIT_EXECUTABLE}" status --porcelain
                        WORKING_DIRECTORY "${SRCDIR}"
                        OUTPUT_VARIABLE _dirty OUTPUT_STRIP_TRAILING_WHITESPACE
                        ERROR_QUIET)
        if(NOT _dirty STREQUAL "")
            set(_hash "${_hash}+local")
        endif()
    endif()
endif()

set(_text "// generated by cmake/gitversion.cmake - do not edit\n#define VIEWER_VERSION_STR \"${_hash}\"\n")

# Only rewrite when it changed, or every build would relink for nothing.
set(_old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" _old)
endif()
if(NOT _old STREQUAL _text)
    file(WRITE "${OUT}" "${_text}")
    message(STATUS "viewer version: ${_hash}")
endif()
